import useUserScores from "./../../hooks/user-scores/useUserScores.ts";
import type { UserScoreResponseDataT } from "./../../../server/routes/user-scores/domains/models.ts";
import "./TopUsers.css";

export default function TopUsers() {
  const { userScores } = useUserScores();

  const downloadCsv = async () => {
    const url = "/api/user-scores/csv";

    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(`Failed to download CSV: ${res.status} ${res.statusText}`);
    }

    const blob = await res.blob();
    const objectUrl = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = objectUrl;
    a.download = "latest-user-scores.csv";
    document.body.appendChild(a);
    a.click();
    a.remove();

    URL.revokeObjectURL(objectUrl);
  };

  return (
    <div id="top-users">
      <div className="top-users__grid">
        <section className="top-users__scores">
          <h3>Top Farcaster User Scores</h3>
          <table className="top-users__table">
            <thead>
              <tr>
                <th className="top-users__th-fid">FID</th>
                <th className="top-users__th-score">Pagerank</th>
              </tr>
            </thead>
            <tbody>
              {userScores.map((userScore: UserScoreResponseDataT) => (
                <tr key={userScore.fid}>
                  <td className="top-users__td-fid">{userScore.fid}</td>
                  <td className="top-users__td-score">
                    {userScore.scores?.pagerank ?? 0}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <aside className="top-users__download">
          <h3>Download Raw Scores</h3>
          <p className="top-users__download-desc">
            CSV file with FID and Pagerank scores generated by interaction weight.
          </p>
          <button type="button" onClick={downloadCsv} className="top-users__download-btn">
            Download CSV
          </button>
        </aside>
      </div>
    </div>
  );
}
